path_classifiers:
  test:
    # Override LGTM's default classification of test files by excluding all files.
    - exclude: /
    # Classify all files in the following listed paths as tests
    - src/tests
    - src/benchmarks

  generated:
    # Exclude the Cython-generated module C++ code that was committed for a long time.
    - exclude: **/indexed_bzip2.cpp
    # By default, all files not checked into the repository are considered to be 'generated'.

  # The default behavior is to tag library code as `library`. Results are hidden
  # for library code. You can tag further files as being library code by adding them
  # to the `library` section.
  library:
    - exclude: src/external

extraction:
  cpp:
     after_prepare:
        - "mkdir custom_cmake"
        - "wget --quiet -O - https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-linux-x86_64.tar.gz | tar --strip-components=1 -xz -C custom_cmake"
        - "export PATH=$(pwd)/custom_cmake/bin:${PATH}"
     index:
        build_command:
        - cmake .
