name: Build Wheels for pragzip

on:
  push:
    branches: 'develop'

jobs:
  Build-Wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        # manylinux1 is not supported anymore because it won't compile C++17 code
        # manylinux2010 runs into this problem https://github.com/pypa/cibuildwheel/issues/1001
        # MacOS and Windows ignore the manylinux-image version because they are not Linux.
        include:
        - os: ubuntu-latest
          manylinux-image: manylinux2014
        - os: ubuntu-latest
          manylinux-image: manylinux_2_28
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade-strategy eager --upgrade cython twine cibuildwheel build

    - name: Build Tarball
      working-directory: python/pragzip
      run: python3 -m build --sdist

    - name: Build x86-64 Wheels
      env:
        CIBW_ARCHS: auto64
        CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux-image }}
      run: python -m cibuildwheel --output-dir dist python/pragzip

    - name: Build i686 Wheels
      if: matrix.manylinux-image == 'manylinux2014' && matrix.os != 'macos-latest'
      env:
        CIBW_ARCHS: auto32
        CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux-image }}
      run: python -m cibuildwheel --output-dir dist python/pragzip

    - name: Check Wheels
      run: twine check dist/* python/pragzip/dist/*
