name: Build Wheels

on:
  push:
    branches: 'master'

jobs:
  Build-Wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # manylinux1 is not supported anymore because it won't compile C++17 code
        # manylinux_2_24, which is newer than manylinux2014, is not supported because it comes with GCC 5.3,
        # which cannot compile C++17 code. Just why?
        # https://github.com/pypa/manylinux/issues/1012
        # manylinux2010 runs into this problem https://github.com/pypa/cibuildwheel/issues/1001
        manylinux-image: [manylinux2014]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade-strategy eager --upgrade cython twine cibuildwheel build

    - name: Build Tarball
      working-directory: python/indexed_bzip2
      if: matrix.manylinux-image == 'manylinux_2014' && matrix.os == 'ubuntu-latest'
      run: python3 -m build --sdist

    - name: Build Wheels
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux-image }}
        CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux-image }}
      run: python -m cibuildwheel --output-dir dist python/indexed_bzip2

    - name: Check Wheels
      run: twine check dist/*
